name: Send Git Logs via Email

on:
  workflow_dispatch:
    inputs:
      since:
        description: "Number of recent commits to include"
        required: false
        default: '5' 
      email:
        description: 'Recipient email address'
        required: true
        default: 'shubharavi687@gmail.com'

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Git Logs
        run: |
          git log ${{ github.event.inputs.since }}..HEAD > git_logs.txt
          echo "Generated git_logs.txt:"
          cat git_logs.txt

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: shubharavi687@gmail.com
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Git Logs Notification
          to: ${{ github.event.inputs.email }}
          from: GitHub Bot <shubharavikumar@gmail.com>
          body: |
            Git logs from ${{ github.event.inputs.since }} to HEAD are attached.
          attachments: git_logs.txt
