# .github/workflows/Demo.yml

name: Email Notification

on:
  push:
    branches:
      - main  # or your target branch

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: GitHub Actions Workflow Notification
          to: shubharavi687@gmail.com
          from: Your GitHub Bot <bot@example.com>
          content_type: text/plain
          body: |
            ✅ GitHub Actions Workflow Completed!
            Repo: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Actor: ${{ github.actor }}
